### ISSUE TITLE
Errors on NPM Start

### ISSUE THREAD

**Issue by LJAM96** [litdevelopers/tinder#18] opened 2017-02-21 01:07 UTC
I've tried to follow the instructions a few times but I keep getting the same issue on npm start which is 

> Error: Cannot find module 'tinder'

Any Ideas?
>C:\Users\Luke>cd tinder
>C:\Users\Luke\tinder>npm start

> > react-boilerplate@3.0.0 start C:\Users\Luke\tinder
> cross-env NODE_ENV=development babel-watch server

> Error:  Cannot find module 'tinder'
>    at Function.Module._resolveFilename (module.js:469:15)
>    at Function.Module._load (module.js:417:25)
>    at Module.require (module.js:497:17)
>    at require (internal/module.js:20:19)
>    at Object.<anonymous> (C:\Users\Luke\tinder\server\api\api.js:2:16)
>    at Module._compile (module.js:570:32)
>    at babelWatchLoader (C:\Users\Luke\tinder\node_modules\babel-watch\runner.js:50:13)
>    at Object.require.extensions.(anonymous function) [as .js] 
>(C:\Users\Luke\tinder\node_modules\babel-watch\runner.js:61:7)
>    at Module.load (module.js:487:32)
>    at tryModuleLoad (module.js:446:12)

**Comment by shellbotx** [comment] 2017-02-25 01:56
Getting the same error. Working on a fix now.

What do you get when you run npm install again? I receive: "ERROR in dll reactBoilerplateDeps"

**Comment by eddiewang** [comment] 2017-02-25 05:30
woops. sorry guys. been busy with life and didn't notice this until now.
my fault. I'm currently working on a newer version with a simpler UI and better client side performance, and in doing so I accidentally updated the api not realizing the old app still looked for the old dependency, which no longer exists...

I've gone ahead and reverted the branch, so if you try using yarn or npm install again it should work this time.

Cheers!

**Comment by gavingimbo** [comment] 2017-02-25 15:14
Hi!

It seems as of February 25, I still face the same issue as everyone has mentioned.

Not sure what's wrong. I've tried reinstalling node.js (windows), ran a fresh git clone of the repo, issue still persists.

**Comment by eddiewang** [comment] 2017-02-25 23:40
give it a shot now.

**Comment by fedecupe** [comment] 2017-02-26 00:05
made freshi git clone, still problems
[npm-debug.log.new.txt](https://github.com/litdevelopers/tinder/files/801638/npm-debug.log.new.txt)

**Comment by eddiewang** [comment] 2017-02-26 00:06
@fedecupe hmm. what version of node are you using?

**Comment by eddiewang** [comment] 2017-02-26 00:07
@shellbotx dm'ed me via twitter and reported that it was working.

**Comment by fedecupe** [comment] 2017-02-26 09:33
@eddiewang nodejs is already the newest version (4.2.6~dfsg-1ubuntu4.1).

**Comment by LJAM96** [comment] 2017-02-26 12:49
Thanks the update, works perfectly for me

**Comment by eddiewang** [comment] 2017-02-26 18:00
@fedecupe you need to upgrade node to v6, because I probably used es6 somewhere in my server code out of bad habits. just 
`npm install -g n 
n latest
yarn
`

try that

**Comment by fedecupe** [comment] 2017-02-26 19:16
So, it requested I do this as root
` npm install -g n n latest yarn
npm WARN deprecated yarn@0.20.3: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install
npm WARN checkPermissions Missing write access to /usr/local/lib
/usr/local/lib
├─┬ latest@0.2.0 
│ └─┬ npm@2.15.11 
│   ├── abbrev@1.0.9 
│   ├── ansi@0.3.1 
│   ├── ansi-regex@2.0.0 
│   ├── ansicolors@0.3.2 
│   ├── ansistyles@0.1.3 
│   ├── archy@1.0.0 
│   ├── async-some@1.0.2 
│   ├── block-stream@0.0.9 
│   ├── char-spinner@1.0.1 
│   ├── chmodr@1.0.2 
│   ├── chownr@1.0.1 
│   ├── cmd-shim@2.0.2 
│   ├─┬ columnify@1.5.4 
│   │ └─┬ wcwidth@1.0.0 
│   │   └─┬ defaults@1.0.3 
│   │     └── clone@1.0.2 
│   ├─┬ config-chain@1.1.10 
│   │ └── proto-list@1.2.4 
│   ├─┬ dezalgo@1.0.3 
│   │ └── asap@2.0.3 
│   ├── editor@1.0.0 
│   ├── fs-vacuum@1.2.9 
│   ├─┬ fs-write-stream-atomic@1.0.8 
│   │ └── iferr@0.1.5 
│   ├── fstream@1.0.10 
│   ├─┬ fstream-npm@1.1.1 
│   │ └── fstream-ignore@1.0.5 
│   ├── github-url-from-git@1.4.0 
│   ├── github-url-from-username-repo@1.0.2 
│   ├─┬ glob@7.0.6 
│   │ ├── fs.realpath@1.0.0 
│   │ └── path-is-absolute@1.0.0 
│   ├── graceful-fs@4.1.6 
│   ├── hosted-git-info@2.1.5 
│   ├── imurmurhash@0.1.4 
│   ├── inflight@1.0.5 
│   ├── inherits@2.0.3 
│   ├── ini@1.3.4 
│   ├─┬ init-package-json@1.9.4 
│   │ ├─┬ glob@6.0.4 
│   │ │ └── path-is-absolute@1.0.0 
│   │ └── promzard@0.3.0 
│   ├── lockfile@1.0.1 
│   ├─┬ lru-cache@4.0.1 
│   │ ├── pseudomap@1.0.2 
│   │ └── yallist@2.0.0 
│   ├─┬ minimatch@3.0.3 
│   │ └─┬ brace-expansion@1.1.6 
│   │   ├── balanced-match@0.4.2 
│   │   └── concat-map@0.0.1 
│   ├─┬ mkdirp@0.5.1 
│   │ └── minimist@0.0.8 
│   ├─┬ node-gyp@3.4.0 
│   │ └─┬ path-array@1.0.1 
│   │   └─┬ array-index@1.0.0 
│   │     ├─┬ debug@2.2.0 
│   │     │ └── ms@0.7.1 
│   │     └─┬ es6-symbol@3.1.0 
│   │       ├── d@0.1.1 
│   │       └─┬ es5-ext@0.10.12 
│   │         └── es6-iterator@2.0.0 
│   ├── nopt@3.0.6 
│   ├── normalize-git-url@3.0.2 
│   ├─┬ normalize-package-data@2.3.5 
│   │ └─┬ is-builtin-module@1.0.0 
│   │   └── builtin-modules@1.1.0 
│   ├── npm-cache-filename@1.0.2 
│   ├── npm-install-checks@1.0.7 
│   ├── npm-package-arg@4.1.0 
│   ├─┬ npm-registry-client@7.2.1 
│   │ ├─┬ concat-stream@1.5.2 
│   │ │ ├─┬ readable-stream@2.0.6 
│   │ │ │ ├── core-util-is@1.0.2 
│   │ │ │ ├── isarray@1.0.0 
│   │ │ │ ├── process-nextick-args@1.0.7 
│   │ │ │ ├── string_decoder@0.10.31 
│   │ │ │ └── util-deprecate@1.0.2 
│   │ │ └── typedarray@0.0.6 
│   │ └── retry@0.10.0 
│   ├── npm-user-validate@0.1.5 
│   ├─┬ npmlog@2.0.4 
│   │ ├─┬ are-we-there-yet@1.1.2 
│   │ │ └── delegates@1.0.0 
│   │ └─┬ gauge@1.2.7 
│   │   ├── has-unicode@2.0.0 
│   │   ├─┬ lodash.pad@4.4.0 
│   │   │ ├── lodash._baseslice@4.0.0 
│   │   │ ├── lodash._basetostring@4.12.0 
│   │   │ └── lodash.tostring@4.1.4 
│   │   ├── lodash.padend@4.5.0 
│   │   └── lodash.padstart@4.5.0 
│   ├── once@1.4.0 
│   ├── opener@1.4.1 
│   ├─┬ osenv@0.1.3 
│   │ ├── os-homedir@1.0.0 
│   │ └── os-tmpdir@1.0.1 
│   ├── path-is-inside@1.0.1 
│   ├─┬ read@1.0.7 
│   │ └── mute-stream@0.0.5 
│   ├─┬ read-installed@4.0.3 
│   │ ├── debuglog@1.0.1 
│   │ ├── readdir-scoped-modules@1.0.2 
│   │ └── util-extend@1.0.1 
│   ├─┬ read-package-json@2.0.4 
│   │ ├─┬ glob@6.0.4 
│   │ │ └── path-is-absolute@1.0.0 
│   │ └─┬ json-parse-helpfulerror@1.0.3 
│   │   └── jju@1.3.0 
│   ├─┬ readable-stream@2.1.5 
│   │ ├── buffer-shims@1.0.0 
│   │ ├── core-util-is@1.0.2 
│   │ ├── isarray@1.0.0 
│   │ ├── process-nextick-args@1.0.7 
│   │ ├── string_decoder@0.10.31 
│   │ └── util-deprecate@1.0.2 
│   ├── realize-package-specifier@3.0.1 
│   ├─┬ request@2.74.0 
│   │ ├── aws-sign2@0.6.0 
│   │ ├── aws4@1.4.1 
│   │ ├─┬ bl@1.1.2 
│   │ │ └─┬ readable-stream@2.0.6 
│   │ │   ├── core-util-is@1.0.2 
│   │ │   ├── isarray@1.0.0 
│   │ │   ├── process-nextick-args@1.0.7 
│   │ │   ├── string_decoder@0.10.31 
│   │ │   └── util-deprecate@1.0.2 
│   │ ├── caseless@0.11.0 
│   │ ├─┬ combined-stream@1.0.5 
│   │ │ └── delayed-stream@1.0.0 
│   │ ├── extend@3.0.0 
│   │ ├── forever-agent@0.6.1 
│   │ ├─┬ form-data@1.0.0-rc4 
│   │ │ └── async@1.5.2 
│   │ ├─┬ har-validator@2.0.6 
│   │ │ ├─┬ chalk@1.1.3 
│   │ │ │ ├── ansi-styles@2.2.1 
│   │ │ │ ├── escape-string-regexp@1.0.5 
│   │ │ │ ├── has-ansi@2.0.0 
│   │ │ │ └── supports-color@2.0.0 
│   │ │ ├─┬ commander@2.9.0 
│   │ │ │ └── graceful-readlink@1.0.1 
│   │ │ ├─┬ is-my-json-valid@2.13.1 
│   │ │ │ ├── generate-function@2.0.0 
│   │ │ │ ├─┬ generate-object-property@1.2.0 
│   │ │ │ │ └── is-property@1.0.2 
│   │ │ │ ├── jsonpointer@2.0.0 
│   │ │ │ └── xtend@4.0.1 
│   │ │ └─┬ pinkie-promise@2.0.1 
│   │ │   └── pinkie@2.0.4 
│   │ ├─┬ hawk@3.1.3 
│   │ │ ├── boom@2.10.1 
│   │ │ ├── cryptiles@2.0.5 
│   │ │ ├── hoek@2.16.3 
│   │ │ └── sntp@1.0.9 
│   │ ├─┬ http-signature@1.1.1 
│   │ │ ├── assert-plus@0.2.0 
│   │ │ ├─┬ jsprim@1.3.0 
│   │ │ │ ├── extsprintf@1.0.2 
│   │ │ │ ├── json-schema@0.2.2 
│   │ │ │ └── verror@1.3.6 
│   │ │ └─┬ sshpk@1.9.2 
│   │ │   ├── asn1@0.2.3 
│   │ │   ├── assert-plus@1.0.0 
│   │ │   ├── dashdash@1.14.0 
│   │ │   ├── ecc-jsbn@0.1.1 
│   │ │   ├── getpass@0.1.6 
│   │ │   ├── jodid25519@1.0.2 
│   │ │   ├── jsbn@0.1.0 
│   │ │   └── tweetnacl@0.13.3 
│   │ ├── is-typedarray@1.0.0 
│   │ ├── isstream@0.1.2 
│   │ ├── json-stringify-safe@5.0.1 
│   │ ├─┬ mime-types@2.1.11 
│   │ │ └── mime-db@1.23.0 
│   │ ├── node-uuid@1.4.7 
│   │ ├── oauth-sign@0.8.2 
│   │ ├── qs@6.2.1 
│   │ ├── stringstream@0.0.5 
│   │ ├── tough-cookie@2.3.1 
│   │ └── tunnel-agent@0.4.3 
│   ├── retry@0.10.0 
│   ├── rimraf@2.5.4 
│   ├── semver@5.1.0 
│   ├─┬ sha@2.0.1 
│   │ └─┬ readable-stream@2.0.2 
│   │   ├── core-util-is@1.0.1 
│   │   ├── isarray@0.0.1 
│   │   ├── process-nextick-args@1.0.3 
│   │   ├── string_decoder@0.10.31 
│   │   └── util-deprecate@1.0.1 
│   ├── slide@1.1.6 
│   ├── sorted-object@2.0.0 
│   ├── spdx-license-ids@1.2.2 
│   ├── strip-ansi@3.0.1 
│   ├── tar@2.2.1 
│   ├── text-table@0.2.0 
│   ├── uid-number@0.0.6 
│   ├── umask@1.1.0 
│   ├─┬ validate-npm-package-license@3.0.1 
│   │ ├── spdx-correct@1.0.2 
│   │ └─┬ spdx-expression-parse@1.0.2 
│   │   └── spdx-exceptions@1.0.4 
│   ├─┬ validate-npm-package-name@2.2.2 
│   │ └── builtins@0.0.7 
│   ├─┬ which@1.2.11 
│   │ └── isexe@1.1.2 
│   ├── wrappy@1.0.2 
│   └── write-file-atomic@1.1.4 
├── n@2.1.4 
└─┬ yarn@0.20.3 
  ├─┬ babel-runtime@6.23.0 
  │ ├── core-js@2.4.1 
  │ └── regenerator-runtime@0.10.3 
  ├── bytes@2.4.0 
  ├── camelcase@3.0.0 
  ├─┬ chalk@1.1.3 
  │ ├── ansi-styles@2.2.1 
  │ ├── escape-string-regexp@1.0.5 
  │ ├─┬ has-ansi@2.0.0 
  │ │ └── ansi-regex@2.1.1 
  │ ├── strip-ansi@3.0.1 
  │ └── supports-color@2.0.0 
  ├─┬ cmd-shim@2.0.2 
  │ └── graceful-fs@4.1.11 
  ├─┬ commander@2.9.0 
  │ └── graceful-readlink@1.0.1 
  ├── death@1.1.0 
  ├─┬ debug@2.6.1 
  │ └── ms@0.7.2 
  ├─┬ defaults@1.0.3 
  │ └── clone@1.0.2 
  ├── detect-indent@5.0.0 
  ├── diff@2.2.3 
  ├── ini@1.3.4 
  ├─┬ inquirer@3.0.4 
  │ ├── ansi-escapes@1.4.0 
  │ ├─┬ cli-cursor@2.1.0 
  │ │ └─┬ restore-cursor@2.0.0 
  │ │   └─┬ onetime@2.0.0 
  │ │     └── mimic-fn@1.1.0 
  │ ├── cli-width@2.1.0 
  │ ├─┬ external-editor@2.0.1 
  │ │ └── tmp@0.0.31 
  │ ├── figures@2.0.0 
  │ ├── lodash@4.17.4 
  │ ├── mute-stream@0.0.7 
  │ ├─┬ run-async@2.3.0 
  │ │ └── is-promise@2.1.0 
  │ ├── rx@4.1.0 
  │ ├─┬ string-width@2.0.0 
  │ │ └── is-fullwidth-code-point@2.0.0 
  │ └── through@2.3.8 
  ├─┬ invariant@2.2.2 
  │ └─┬ loose-envify@1.3.1 
  │   └── js-tokens@3.0.1 
  ├─┬ is-builtin-module@1.0.0 
  │ └── builtin-modules@1.1.1 
  ├─┬ is-ci@1.0.10 
  │ └── ci-info@1.0.0 
  ├── leven@2.1.0 
  ├─┬ loud-rejection@1.6.0 
  │ ├─┬ currently-unhandled@0.4.1 
  │ │ └── array-find-index@1.0.2 
  │ └── signal-exit@3.0.2 
  ├─┬ minimatch@3.0.3 
  │ └─┬ brace-expansion@1.1.6 
  │   ├── balanced-match@0.4.2 
  │   └── concat-map@0.0.1 
  ├─┬ mkdirp@0.5.1 
  │ └── minimist@0.0.8 
  ├─┬ node-emoji@1.5.1 
  │ └── string.prototype.codepointat@0.2.0 
  ├─┬ node-gyp@3.5.0 
  │ ├── fstream@1.0.10 
  │ ├─┬ glob@7.1.1 
  │ │ ├── fs.realpath@1.0.0 
  │ │ ├─┬ inflight@1.0.6 
  │ │ │ └── wrappy@1.0.2 
  │ │ ├── once@1.4.0 
  │ │ └── path-is-absolute@1.0.1 
  │ ├─┬ nopt@3.0.6 
  │ │ └── abbrev@1.1.0 
  │ ├─┬ npmlog@4.0.2 
  │ │ ├─┬ are-we-there-yet@1.1.2 
  │ │ │ └── delegates@1.0.0 
  │ │ ├── console-control-strings@1.1.0 
  │ │ ├─┬ gauge@2.7.3 
  │ │ │ ├── aproba@1.1.1 
  │ │ │ ├── has-unicode@2.0.1 
  │ │ │ ├── object-assign@4.1.1 
  │ │ │ ├─┬ string-width@1.0.2 
  │ │ │ │ ├── code-point-at@1.1.0 
  │ │ │ │ └─┬ is-fullwidth-code-point@1.0.0 
  │ │ │ │   └── number-is-nan@1.0.1 
  │ │ │ └─┬ wide-align@1.1.0 
  │ │ │   └─┬ string-width@1.0.2 
  │ │ │     └── is-fullwidth-code-point@1.0.0 
  │ │ └── set-blocking@2.0.0 
  │ ├─┬ osenv@0.1.4 
  │ │ └── os-tmpdir@1.0.2 
  │ └─┬ which@1.2.12 
  │   └── isexe@1.1.2 
  ├── object-path@0.11.3 
  ├─┬ proper-lockfile@2.0.0 
  │ └── retry@0.10.1 
  ├── read@1.0.7 
  ├─┬ request@2.79.0 
  │ ├── aws-sign2@0.6.0 
  │ ├── aws4@1.6.0 
  │ ├── caseless@0.11.0 
  │ ├─┬ combined-stream@1.0.5 
  │ │ └── delayed-stream@1.0.0 
  │ ├── extend@3.0.0 
  │ ├── forever-agent@0.6.1 
  │ ├─┬ form-data@2.1.2 
  │ │ └── asynckit@0.4.0 
  │ ├─┬ har-validator@2.0.6 
  │ │ ├─┬ is-my-json-valid@2.16.0 
  │ │ │ ├── generate-function@2.0.0 
  │ │ │ ├─┬ generate-object-property@1.2.0 
  │ │ │ │ └── is-property@1.0.2 
  │ │ │ └── jsonpointer@4.0.1 
  │ │ └─┬ pinkie-promise@2.0.1 
  │ │   └── pinkie@2.0.4 
  │ ├─┬ hawk@3.1.3 
  │ │ ├── boom@2.10.1 
  │ │ ├── cryptiles@2.0.5 
  │ │ ├── hoek@2.16.3 
  │ │ └── sntp@1.0.9 
  │ ├─┬ http-signature@1.1.1 
  │ │ ├── assert-plus@0.2.0 
  │ │ ├─┬ jsprim@1.3.1 
  │ │ │ ├── extsprintf@1.0.2 
  │ │ │ ├── json-schema@0.2.3 
  │ │ │ └── verror@1.3.6 
  │ │ └─┬ sshpk@1.10.2 
  │ │   ├── asn1@0.2.3 
  │ │   ├── assert-plus@1.0.0 
  │ │   ├── bcrypt-pbkdf@1.0.1 
  │ │   ├─┬ dashdash@1.14.1 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── ecc-jsbn@0.1.1 
  │ │   ├─┬ getpass@0.1.6 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── jodid25519@1.0.2 
  │ │   ├── jsbn@0.1.1 
  │ │   └── tweetnacl@0.14.5 
  │ ├── is-typedarray@1.0.0 
  │ ├── isstream@0.1.2 
  │ ├── json-stringify-safe@5.0.1 
  │ ├─┬ mime-types@2.1.14 
  │ │ └── mime-db@1.26.0 
  │ ├── oauth-sign@0.8.2 
  │ ├── qs@6.3.1 
  │ ├── stringstream@0.0.5 
  │ ├─┬ tough-cookie@2.3.2 
  │ │ └── punycode@1.4.1 
  │ ├── tunnel-agent@0.4.3 
  │ └── uuid@3.0.1 
  ├── request-capture-har@1.1.4 
  ├── rimraf@2.6.1 
  ├── roadrunner@1.1.0 
  ├── semver@5.3.0 
  ├── strip-bom@3.0.0 
  ├─┬ tar@2.2.1 
  │ ├── block-stream@0.0.9 
  │ └── inherits@2.0.3 
  ├─┬ tar-stream@1.5.2 
  │ ├── bl@1.2.0 
  │ ├─┬ end-of-stream@1.1.0 
  │ │ └── once@1.3.3 
  │ ├─┬ readable-stream@2.2.3 
  │ │ ├── buffer-shims@1.0.0 
  │ │ ├── core-util-is@1.0.2 
  │ │ ├── isarray@1.0.0 
  │ │ ├── process-nextick-args@1.0.7 
  │ │ ├── string_decoder@0.10.31 
  │ │ └── util-deprecate@1.0.2 
  │ └── xtend@4.0.1 
  ├─┬ user-home@2.0.0 
  │ └── os-homedir@1.0.2 
  └─┬ validate-npm-package-license@3.0.1 
    ├─┬ spdx-correct@1.0.2 
    │ └── spdx-license-ids@1.2.2 
    └── spdx-expression-parse@1.0.4 

npm ERR! Linux 4.9.5-040905-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "n" "n" "latest" "yarn"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /usr/local/lib
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/federico/Scaricati/tinder/npm-debug.log
`

and then this
`
 npm start

> react-boilerplate@3.0.0 start /home/federico/Scaricati/tinder
> cross-env NODE_ENV=development babel-watch server

/usr/bin/env: "node": File o directory non esistente

npm ERR! Linux 4.9.5-040905-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! react-boilerplate@3.0.0 start: `cross-env NODE_ENV=development babel-watch server`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.0.0 start script 'cross-env NODE_ENV=development babel-watch server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development babel-watch server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/federico/Scaricati/tinder/npm-debug.log
`

[npm-debug.log.txt](https://github.com/litdevelopers/tinder/files/802192/npm-debug.log.txt)

**Comment by shellbotx** [comment] 2017-02-27 06:18
@fedecupe You're still running node v4, you need to update to >= node v6

If you're attempting to install via `apt-get install nodejs` and getting that your package is already "up to date" then you should attempt using [nvm](https://github.com/creationix/nvm) or building from node v6 source.

I recommend nvm, then you can easily bounce around different versions of node!

P.S. You need to use `sudo` for `npm install -g`, that's what's causing the "permission denied" errors.

**Comment by fedecupe** [comment] 2017-02-27 09:26
Ok, I feel we are almost there.. (almost)
Updated node.js, modified saga.js with extension id, run npm install, then
` ` `
federico@federico-XPS:~/Scaricati/tinder$ sudo npm install -g n n latest yarn
npm WARN deprecated yarn@0.20.3: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install
/usr/local/bin/latest -> /usr/local/lib/node_modules/latest/bin/latest.js
/usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
/usr/local/bin/yarn -> /usr/local/lib/node_modules/yarn/bin/yarn.js
/usr/local/bin/yarnpkg -> /usr/local/lib/node_modules/yarn/bin/yarn.js
/usr/local/lib
├── latest@0.2.0 
├── n@2.1.4 
└── yarn@0.20.3 

federico@federico-XPS:~/Scaricati/tinder$ npm start

> react-boilerplate@3.0.0 start /home/federico/Scaricati/tinder
> cross-env NODE_ENV=development babel-watch server

Server started ✓

Access URLs:
-----------------------------------
Localhost: http://localhost:3000
      LAN: http://159.149.230.52:3000
-----------------------------------
Press CTRL-C to stop
    
webpack built 84e51f3452b773dd20f5 in 6932ms

ERROR in ./app/static/conversation.png
Module build failed: Error: spawn /home/federico/Scaricati/tinder/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./app/containers/Messages/index.js 67:0-62

ERROR in ./app/static/tinder_female.png
Module build failed: Error: spawn /home/federico/Scaricati/tinder/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./app/components/Panel/index.js 6:0-56

ERROR in ./app/static/tinder_male.png
Module build failed: Error: spawn /home/federico/Scaricati/tinder/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./app/components/Panel/index.js 7:0-52
Child html-webpack-plugin for "index.html":

` ` `

**Comment by eddiewang** [comment] 2017-02-27 17:12
looks like pngquant isn't working. common windows problem. it's a permissions issue. ensure you're installing everything with admin privs. closing issue as it's not a bug with the application itself.

**Closed by eddiewang** 2017-02-27 17:12 UTC
