### ISSUE TITLE
Facebook Authorisation doesn't redirect to your app

### ISSUE THREAD

**Issue by alimohyudin** [litdevelopers/tinder#27] opened 2017-03-25 13:59 UTC
Hi, I'm trying to run your chrome app, it's started perfectly as it should but on the login page of facebook when it says "You have already authorised Tinder." I press OK but it doesn't  go to any other page of your app. Can you please help me with that? Also there's no error on command line. Thanks
![image](https://cloud.githubusercontent.com/assets/15377783/24322805/fd9ea686-118c-11e7-8a97-8a982109f1f6.png)

**Comment by wwboynton** [comment] 2017-03-25 16:57
It seems like you might have a conflicting extension installed, like [Flamite](https://chrome.google.com/webstore/detail/flamite/dcpgcfkjhjmicodpdobmilikmjknfofp), which is dead now. I had the same issue. If you have another extension that serves the same purpose, try disabling it and then giving it another shot.

**Comment by eddiewang** [comment] 2017-03-29 13:41
@alimohyudin @wwboynton it's a conflicting extension issue. Delete flamite and try again. Also, you have to be logged into facebook first before using the extension.

If someone can fix / improve on this process a PR would be greatly appreciated.

**Comment by eddiewang** [comment] 2017-05-12 13:28
closing this because it's not a bug and currently works just fine.

**Closed by eddiewang** 2017-05-12 13:28 UTC
Labels: help wanted
